language: node_js
os:
  - linux
dist: xenial
node_js:
  - 14
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm set progress=false
  - npm install
before_script:
  - [ "$TRAVIS_OS_NAME" = "linux" ] && [[ "$TRAVIS_NODE_VERSION" =~ "v14." ]] && { curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build }
script:
  - npm run prettier-check
  - npm run lint
  - npm run build-commonjs
  - npm run build-esm
  - npm test
after_script:
  - [ "$TRAVIS_OS_NAME" = "linux" ] && [[ "$TRAVIS_NODE_VERSION" =~ "v14." ]] && { ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT }
